config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'
  resources :warehouses do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :show, :create, :new, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      patch :delivered
      patch :canceled
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[show index create]
      post 'stock_update', to: 'stock_products#stock_update'
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  
  validates :name, :wight, :width, :height, :depth, :supplier, :sku, presence: true
  validates :width, :wight, :height, :depth, numericality: { greater_than: 0 }
  validates :sku, length: { is: 20 }
  validates :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_admin!, only: [:index]

  def index
    @product_models = ProductModel.all
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  def new
    @suppliers = Supplier.all
    @product_model = ProductModel.new
  end

  def create
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to product_model_path(@product_model.id), notice: 'Modelo de produto cadastrado com sucesso'
    else
      @suppliers = Supplier.all
      flash[:notice] = 'Falha ao cadastrar, preencha os dados corretamente'
      render :new
    end
  end

  def edit
    @suppliers = Supplier.all
    @product_model = ProductModel.find(params[:id])
  end

  def update
    @product_model = ProductModel.find(params[:id])

    if @product_model.update(product_model_params)
      redirect_to product_model_path, notice: 'Modelo de produto atualizado com sucesso'
    else
      @suppliers = Supplier.all
      flash[:notice] = 'Falha ao atualizar, preencha os dados corretamente'
      render :new
    end
  end

  def product_model_params
    params.require(:product_model).permit(:name, :wight, :width, :height, :depth, :supplier_id, :sku)
  end
end

app/views/product_models/_formp.html.erb
<section class='container'>
<%= form_with model: @product_model, html: { class: 'form'} do |f| %>
    <div>
        <h1>Novo Modelo de produto</h1>

        <div class='field'>
            <%= f.label :name %> 
            <%= f.text_field :name %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:name).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :sku%>
            <%= f.text_field :sku %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:sku).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :supplier_id, 'Fornecedor' %>
            <%= f.collection_select :supplier_id, @suppliers, :id, :fantasy_name %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:supplier_id).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :wight%>
            <%= f.number_field :wight %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:wight).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :width%>
            <%= f.number_field :width %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:width).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :height %>
            <%= f.number_field :height %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:height).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :depth %>
            <%= f.number_field :depth %>
            <% if @product_model.errors.any?%>
                <p class=' text-red-600'><%= @product_model.errors.full_messages_for(:depth).first %></p>
            <% end %>
        </div>
        <div class='w-full'>
            <%= f.submit 'Enviar', class:'btn-primary w-full'%>
        </div>
    </div>
<% end %>
</section>

app/views/product_models/edit.html.erb
<h1>Editar Modelo de produto</h1>

<%= render 'formp' %>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<% @product_models.each do |pm| %>
  <div>
    <p><%= link_to pm.name, pm%></p>
    <p><%= pm.sku %></p>
    <p><%= pm.supplier.fantasy_name %></p>
  </div>
<% end %>
<% if @product_models.empty? %>
  <p>Não ha modelos cadastrados</p>
<% end %>
<%= link_to 'Cadastrar modelo', new_product_model_path %>

app/views/product_models/new.html.erb
<%= render 'formp' %>

app/views/product_models/show.html.erb
<h1>Modelo de <%= @product_model.name%></h1>

<% if flash[:notice] %>
  <p style='color: green'><%= flash[:notice]%></p>
<% end %>

<section id='product_model'>
    <div>
        <p>Produto: <%= @product_model.name%></p>
        <p>Código SKU: <%= @product_model.sku%></p>
        <p>Fornecedor: <%= @product_model.supplier.fantasy_name%></p>
        <p>Peso: <%= @product_model.wight%> gramas</p>
        <p>Dimensões: <%= @product_model.width%>cm x <%= @product_model.height%>cm x <%= @product_model.depth%>cm </p>
    </div>
    <div>
           
        <%= link_to 'Voltar', root_path%>
        <%= link_to 'Editar', edit_product_model_path%>
    </div>
</section>