config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'
  resources :warehouses do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :show, :create, :new, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      patch :delivered
      patch :canceled
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[show index create]
      post 'stock_update', to: 'stock_products#stock_update'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 5, delivered: 10, canceled: 9 }

  validates :code, :estimated_delivery_date, presence: true
  validate :estimated_delivery_date_is_future

  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :admin
  has_many :order_items
  has_many :product_models, through: :order_items

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    return unless estimated_delivery_date.present? && estimated_delivery_date <= Date.today

    errors.add(:estimated_delivery_date, ' deve ser futura.')
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :check_user, only: %i[show edit update delivered canceled]

  def index
    current_admin && @orders = current_admin.orders
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :admin_id, :estimated_delivery_date)
    @order = Order.new(order_params)
    @order.admin = current_admin
    @order.save
    redirect_to @order, notice: 'Pedido registrado com sucesso'
  end

  def show; end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    order_params = params.require(:order).permit(:warehouse_id, :supplier_id, :admin_id, :estimated_delivery_date)

    if @order.update(order_params)
      redirect_to order_path, notice: 'Pedido atualizado com sucesso.'
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      render :edit
    end
  end

  def search
    @code = params['query']
    @orders = Order.where('code LIKE ?', "%#{@code}%")
  end

  def canceled
    @order.canceled!
    redirect_to order_path
  end

  def delivered
    @order.delivered!

    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(order: @order, product_model: item.product_model, warehouse: @order.warehouse)
      end
    end

    redirect_to order_path
  end

  private

  def check_user
    @order = Order.find(params[:id])
    @order.admin != current_admin && redirect_to(root_path, notice: 'Pedido não existe')
  end
end

app/views/orders/_form.html.erb
<section class="container">
  <%= form_with model: @order, html: { class: 'form'} do |f|%>
    <div>
      <h1><%= Order.model_name.human%></h1>
      <div class='field'>
        <%= f.label :warehouse_id %>
        <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>        
      </div>
      <div class='field'>
        <%= f.label :supplier_id %>
        <%= f.collection_select :supplier_id, @suppliers, :id, :fantasy_name %>
      </div>
      <div class='field'>
        <%= f.label :estimated_delivery_date%>
        <%= f.date_field :estimated_delivery_date %>
        <% if @order.errors.any?%>
          <p class=' text-red-600'><%= @order.errors.full_messages_for(:estimated_delivery_date).first %></p>
        <% end %>
      </div>
      <div class="w-full">
        <%= f.submit 'Gravar', class:'btn-primary w-full'%>
      </div>
    </div>  
  <%end%>
</section>

app/views/orders/_order.html.erb
<h2><%= Order.human_attribute_name(:code)%>: <%=link_to order.code, order%> </h2> 
<h2><%= Order.human_attribute_name(:status)%>: <%=t order.status%></h2>
<h2><%= Order.human_attribute_name(:warehouse_id)%>: <%=order.warehouse.full_description%> </h2> 
<h2><%= Order.human_attribute_name(:supplier_id)%>: <%=order.supplier.fantasy_name%></h2>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
  <%= render @orders %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/search.html.erb
<h1>Resultados da busca por: <%= @code %></h1>
<p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count)%> <%= t(:found, count: @orders.count)%></p>
<%= render @orders %>

app/views/orders/show.html.erb
<h1>Detalhes do Pedido</h1>
<h2><%= Order.model_name.human %> <%= @order.code%></h2>

<% if flash[:notice] %>
  <p style='color: green'><%= flash[:notice]%></p>
<% end %>

<section id='order'>
    <div>
      Status: <%=t @order.status%> 
      <h2><%= Order.human_attribute_name(:warehouse_id)%>: <%= @order.warehouse.full_description%> </h2> 
      <h2><%= Order.human_attribute_name(:supplier_id)%>: <%= @order.supplier.fantasy_name%></h2>
      <h2><%= Order.human_attribute_name(:admin_id)%>: <%= @order.admin.name%> | <%= @order.admin.email%></h2>
      <h2><%= Order.human_attribute_name(:estimated_delivery_date)%>: <%= I18n.localize(@order.estimated_delivery_date) %></h2>        
    </div>
    
    <div>
      <h2>Itens do Pedido</h2>
      <%= link_to 'Adicionar item', new_order_order_item_path(@order) %>
      <% @order.order_items.each do |item|%>
        <%= item.quantity %> x <%= item.product_model.name %>
      <% end %>
    </div>

    <div>
        <%= link_to 'Editar', edit_order_path(@order)%>
        <%= button_to 'Entregue', delivered_order_path(@order), method: :patch%>
        <%= button_to 'Cancelado', canceled_order_path(@order), method: :patch%>
    </div>
</section>