config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'
  resources :warehouses do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :show, :create, :new, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      patch :delivered
      patch :canceled
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[show index create]
      post 'stock_update', to: 'stock_products#stock_update'
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :fantasy_name, :company_name, :cnpj, :email, presence: true 
  validates :cnpj, uniqueness: true
  validates :cnpj, length: { is: 14 }
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    supplier_params = params.require(:supplier).permit(:fantasy_name, :company_name, :cnpj, :email, :phone, :address)
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor cadastrado com sucesso'
    else
      flash.now[:notice] = 'Falha ao cadastrar'
      render :new
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    supplier_params = params.require(:supplier).permit(:fantasy_name, :company_name, :cnpj, :email, :phone, :address)
    if @supplier.update(supplier_params)
      redirect_to supplier_path(params[:id]), notice: 'Fornecedor editado com sucesso'
    else
      flash.now[:notice] = 'Falha ao editar'
      render :edit
    end
  end
end

app/views/suppliers/_forms.html.erb
<section class="container">
<%= form_with model: @supplier, html: { class: 'form'} do |f| %>
    <div>
        <h1>Novo Fornecedor</h1>

        <div class='field'>
            <%= f.label :fantasy_name %> 
            <%= f.text_field :fantasy_name %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:fantasy_name).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :company_name%>
            <%= f.text_field :company_name %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:company_name).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :cnpj%>
            <%= f.text_field :cnpj %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:cnpj).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :email%>
            <%= f.text_field :email %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:email).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :phone%>
            <%= f.text_field :phone %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:phone).first %></p>
            <% end %>
        </div>
        <div class='field'>
            <%= f.label :address %>
            <%= f.text_field :address %>
            <% if @supplier.errors.any?%>
                <p class=' text-red-600'><%= @supplier.errors.full_messages_for(:address).first %></p>
            <% end %>
        </div>
        <div class='w-full'>
            <%= f.submit 'Enviar', class: 'btn-primary w-full'%>
        </div>
    </div>
<% end %>
</section>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'forms' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>
<% if flash[:notice] %>
  <p style='color: green'><%= flash[:notice]%></p>
<% end %>

<%= link_to 'Cadastrar Fornecedor', new_supplier_path %>

<% @suppliers.each do |s| %>
  <div>
    <p><%=link_to s.fantasy_name, s %></p>
    <p>CNPJ: <%= s.cnpj%></p>
    <p>Email: <%= s.email%></p>
  </div>
<% end %>

<% if @suppliers.empty? %>
  <p>Não existem fornecedores cadastrados</p>
<% end %>

app/views/suppliers/new.html.erb
<%= render 'forms' %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.fantasy_name%></h1>

<% if flash[:notice] %>
  <p style='color: green'><%= flash[:notice]%></p>
<% end %>

<section id='supplier'>
    <div>
        <p>Razão social: <%= @supplier.company_name%></p>
        <p>CNPJ: <%= @supplier.cnpj%></p>
        <p>Email: <%= @supplier.email%></p>
        <p>Telephone: <%= @supplier.phone%></p>
        <p>Endereço: <%= @supplier.address%></p>
    </div>
    <div>
           
        <%= link_to 'Voltar', root_path%>
        <%= link_to 'Editar', edit_supplier_path%>
    </div>
</section>