config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: 'home#index'
  resources :warehouses do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :create, :new, :edit, :update]
  resources :product_models, only: [:index, :show, :create, :new, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      patch :delivered
      patch :canceled
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: %i[show index create]
      post 'stock_update', to: 'stock_products#stock_update'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class='p-5 space-y-3'>
      <nav class=''>
        <%= link_to root_path do %>
        <h1>Galpões e Estoque</h1>
        <% end %>
        <%= link_to 'Fornecedores', suppliers_path%> |
        <%= link_to 'Modelos de produtos', product_models_path%> |
        <%= link_to 'Registrar Pedido', new_order_path%> |
        <%= link_to 'Meus Pedidos', orders_path%> |
        <% if admin_signed_in?%>
        <%= form_with url: search_orders_path, method: :get do |f| %>
          <%= f.label :query, "Buscar pedido" %>
          <%= f.text_field :query %>
          <%= f.submit 'Buscar'%>
        <% end %>
        
          <%= current_admin.name %> |
          <%= current_admin.email %> |
          <%= button_to 'Sair', destroy_admin_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Entrar', new_admin_session_path %>
        <% end %>
      </nav>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </header>
    <%= yield %>
  </body>
</html>